### ISSUE TITLE
Clarify installation method

### ISSUE THREAD

**Issue by TripHumphrey** [chop-analytics/dbt-netezza#1]
I have had mixed success and I will be the first to admit a lack of expertise on this topic, but the process by which this adapter is supposed to be installed is a little confusing.

So far I have had success by looking at a previous iteration of the README.md file that specified a pip install via the git repo link.

I wasn't sure if this is the right method or if it would be preferable to utilize the standard dbt package installation method specified ([here.](https://docs.getdbt.com/docs/building-a-dbt-project/package-management/#how-do-i-add-a-package-to-my-project)

**Comment by joemirizio** [comment]
~Yes, you can (and should) install this adapter just like any other standard dbt package.~

Edit: It looks like the adapter is only recognized by `dbt` when it's installed via `pip`.

**Comment by joemirizio** [comment]
While this will eventually be published to PyPi, you can install it with `pip`:

```sh
pip install git+https://github.com/chop-analytics/dbt-netezza#egg=dbt-netezza
```
