### ISSUE TITLE
'No adapters available' when installing dbt-netezza

### ISSUE THREAD

**Issue by henrikig** [chop-analytics/dbt-netezza#12]
I am trying to install dbt-netezza and create a new dbt project. However, I get an error that no adapters are found.

I manage to install `dbt-netezza` through the following command:
`pip install git+https://github.com/chop-analytics/dbt-netezza`
This installs `dbt-netezza (v0.60)` and `dbt-core (v1.2.0)`. However, when running `dbt init dbt_test`, I receive the following error:
`No adapters available. Go to https://docs.getdbt.com/docs/available-adapters`
I have tried with other adapters (e.g. dbt-postgres), and that works well.
I'm using Python v3.8.9 and pip v22.2.2.

**Comment by cnolanminich** [comment]
Hi @henrikig! Thanks for raising the issue -- we hadn't added the necessary two files (`dbt/include/profile_template.yml` and `dbt/adapters/netezza/__version__.py`) to the adapter, which results in your error. @joemirizio  and I just chatted and will submit a PR shortly to resolve this issue.

Reference: https://docs.getdbt.com/docs/contributing/building-a-new-adapter#other-files

**Comment by stianmikelsen** [comment]
We are very interested in this. Anything we can do to help?

**Comment by cnolanminich** [comment]
this should be resolved now with our latest release: https://github.com/chop-analytics/dbt-netezza/releases/tag/v1.1.0

Please give it a go and let us know if you have any additional issues
