### ISSUE TITLE
model successful but transaction rolled back

### ISSUE THREAD

**Issue by danielefrigo** [chop-analytics/dbt-netezza#16]
In some situations I found that errors from Netezza are not showing (i.e. model results as completed successfully, but transaction has been rolled back or partially committed).
The issue regards incremental models when using delete+insert strategy.

I had to override the get_delete_insert_merge_sql default macro, because the syntax used in the delete statement is not compatible with Netezza (at least not with the NPS version I'm using); I applied really l.ight modifications to make it work properly:

```
{% macro netezza__get_delete_insert_merge_sql(target, source, unique_key, dest_columns) -%}

    {%- set dest_cols_csv = get_quoted_csv(dest_columns | map(attribute="name")) -%}

    {% if unique_key %}
        {% if unique_key is sequence and unique_key is not string %}
            delete from {{target }}
            where ({{ unique_key | join(',') }}) in (
                select {{ unique_key | join(',') }}
                from {{ source }}
            );
        {% else %}
            delete from {{ target }}
            where (
                {{ unique_key }}) in (
                select {{ unique_key }}
                from {{ source }}
            );

        {% endif %}
        {% endif %}

    insert into {{ target }} ({{ dest_cols_csv }})
    (
        select {{ dest_cols_csv }}
        from {{ source }}
    )
{% endmacro %}
```

If I run an incremental model everything works as expects:

```
{{
  config(
    materialized = 'incremental',
    unique_key = 'id'
  )
}}

select 
1 as id,
'aaa' as text,
current_timestamp as load_time
```

If I then manually add a column to the generated table (`alter table test add newattr int`) and re-run the incremental model, I'd expect an error (the new column is not present in the model definition, and thus the INSERT statement should fail), but the models results as completed successfully.
Looking at the data in Netezza, I can see that the whole transaction has been rolled back (you can easily verify it checking the load_time column); in other cases (which I've not been able to reproduce), the DELETE part has been committed but not the INSERT part.

The rollback can be confirmed looking at pg.log on NZ server:

2022-11-30 12:03:55.359100 CET [98500]  DEBUG:  QUERY: delete from GRADWH_TEST.ADMIN.TEST where ( id) in ( select id from GRADWH_TEST.ADMIN.TEST__dbt_tmp ); insert into GRADWH_TEST.ADMIN.TEST ("ID", "TEXT", "LOAD_TIME", "NEWATTR") ( select "ID", "TEXT", "LOAD_TIME", "NEWATTR" from GRADWH_TEST.ADMIN.TEST__dbt_tmp )
2022-11-30 12:03:55.368534 CET [98500]  DEBUG:  transaction 205630955 started dbos txid 0x54a8454
2022-11-30 12:03:55.395208 CET [98500]  DEBUG:  0 rows deleted
2022-11-30 12:03:55.442219 CET [98500]  DEBUG:  1 rows deleted
2022-11-30 12:03:55.459206 CET [98500]  DEBUG:  0 rows deleted
2022-11-30 12:03:55.460414 CET [98500]  ERROR:  Attribute 'NEWATTR' not found
2022-11-30 12:03:55.460962 CET [98500]  DEBUG:  aborted transaction 205630955 (dbos txid 0x54a8454)

I found this issue with both adapter versions 1.1.0 and 0.6.0.

**Comment by danielefrigo** [comment]
Additional element: if I remove `unique_key ` config (to avoid the DELETE step and just append new data), the model rises the expected error message.

**Comment by cnolanminich** [comment]
@danielefrigo which version of `dbt-netezza` are you using? If you're using anything prior to `1.1.0` (latest), we hadn't pulled the correct macros through for `incremental` materializations, and had exactly this issue.

I believe this should be resolved in the latest release, so if it isn't we'll need to investigate

**Comment by danielefrigo** [comment]
I tested it with both 0.6 and 1.1.0, same issue in both versions

**Comment by cnolanminich** [comment]
Hmmm ... I'm wondering if the issue might be that you override the macro without copying all of the boilerplate for the macro? 

I will try to test this myself with a bad "alter table statement" and see if I can replicate

**Comment by danielefrigo** [comment]
What do you mean by boilerplate?
I copied the default macro and just changed minimally the SQL syntax to
make it work on NZ: I removed a pair of round brackets around in the second
version of the DELETE and and changed the first version to use the same
syntax of the second (the USING clause was not working on NZ).
By the way, I got the same issue specifying the unique key both as a string
and as an array.

The key element (per my understanding) is the presence of 2 statements in
the same transaction.

Il mer 30 nov 2022, 20:24 Christian Minich ***@***.***> ha
scritto:

**Comment by danielefrigo** [comment]
Quick update: I've been able to fix the issue slightly changing the above macro.
Since I noticed that the error is visible if dbt doesn't execute the DELETE (i.e. without unique_key in config), I tried separating the calls for the DELETE and the INSERT statements, and now I can see the error as expected.

This is the new version of the macro:

```
{% macro netezza__get_delete_insert_merge_sql(target, source, unique_key, dest_columns) -%}

    {%- set dest_cols_csv = get_quoted_csv(dest_columns | map(attribute="name")) -%}

    {% if unique_key %}
        {% set delete_sql %}
          {% if unique_key is sequence and unique_key is not string %}
              delete from {{target }}
              where ({{ unique_key | join(',') }}) in (
                  select {{ unique_key | join(',') }}
                  from {{ source }}
              );
          {% else %}
              delete from {{ target }}
              where (
                  {{ unique_key }}) in (
                  select {{ unique_key }}
                  from {{ source }}
              );
          {% endif %}
        {% endset %}

    {%- call statement('delete') -%}
      {{ delete_sql }}
    {%- endcall -%}

    {% endif %}

    insert into {{ target }} ({{ dest_cols_csv }})
    (
        select {{ dest_cols_csv }}
        from {{ source }}
    )

{%- endmacro %}
```
