### ISSUE TITLE
PR & Contribution

### ISSUE THREAD

**Issue by Al2a2d2m** [chop-analytics/dbt-netezza#21]
First, thank you for sharing this adapter. I've been using it for a couple of years now, and it helped me so much.

Recently, I needed to gather some meta data (auditability purpose)  and I needed to use dbt_artifacts package. I performed little changes on the code. Do you consider PR & contributions? 

By the way the adapter works fine with dbt-core1.3.5, I upgraded a couple of files to make it work (for my "little" needs) with version 1.6.1 but I am still working on it.

**Comment by joemirizio** [comment]
I'm so glad this has been useful for you! We develop this adapter
internally within our company, and haven't figured out a great workflow for
bringing in external contributions, but this might be something we look
into.

As for the aligning with newer versions of dbt, we just kicked off more
development internally and will hopefully have a 1.2 version in the next
few weeks followed by a 1.3 version soon after. Our goal is to _try_ to
support the full set of features supported by each version of the adapter,
so for 1.2 this involves implementing grants, etc.

This is all to say that while we could just bump the version of `dbt-core`
(which we have done in testing), we are trying to maintain the supported
features as stewards of this package.

**Comment by joemirizio** [comment]
We have since released versions for `dbt-core` 1.2, 1.3, & 1.4 and 1.5 development is underway. We appreciate the support and if there comes a time when this project can accept external contributions, we'll make sure to announce.
