### ISSUE TITLE
Snapshots failing after upgrade to v1.5.0

### ISSUE THREAD

**Issue by henrikig** [chop-analytics/dbt-netezza#24]
Hi!

We are trying to upgrade from dbt-netezza@1.4.0 to dbt-netezza@1.5.0, but are experiencing some issues as the hashing algorithm for snapshot id's seems to have changed (as also mentioned in the [release notes](https://github.com/chop-analytics/dbt-netezza/releases/tag/v1.5.0) for v1.5.0). The error we get is `Bad int8 external representation "<id>"`.

Is there a recommended way of migrating to v1.5.0 while still keeping the old snapshots?

**Comment by joemirizio** [comment]
Yes, sorry about that breaking change and glad you saw the release notes.

dbt has used md5 as their hashing algorithm of choice, whereas we were just
using a simple integer-based hasing function in Netezza. We decided to
adopt their standard to improve compatibility with dbt-core and allow users
to more easily migrate to different databases/adapters.

There are two options moving forward:
- Migrate by rehashing snapshot tables
- Override the adapter snapshot macro with the old hashing function

To migrate, you will want to rehash your snapshot table rows by applying
the new hash function (along with the way dbt joins the columns) to your
hashed data.
1. (Optional) Make a copy of your snapshot tables
2. Alter the column type of the hash column to a VARCHAR
3. Write an UPDATE statement (per table) where the new hash value applies
md5 just like the snapshot macro

The simpler, but less standard approach, would be to retain the previous
functionality by copying the old adapter snapshot macro to your project(s),
which should restore the previous hash method.

We haven't migrated our tables yet, so please let us know how this goes.

**Comment by henrikig** [comment]
Thanks for the quick response. Will hopefully have time to look into this in the near future and update you on our progress. Please also let us know how it goes with you if you have a go at it before us.

Not sure if I should leave this issue open until any of us have actually made the migration, and to potentially let others more easily find it as well. Please do whatever you think is best.

**Comment by henrikig** [comment]
An update on this: We did not have very strict requirements on data integrity, so we simply updated the column from int8 to string without performing a rehash. We then ended up getting some unnecessary updates to the snapshot tables, but it was not a big issue for us.

**Comment by cnolanminich** [comment]
@henrikig  FYI, did some work on this today and wrote the following marco:

It will create `__bkp` versions of all of the snapshots, then drop the old DBT_SCD_ID and create an md5 one. I've tested it on our (13) snapshots and it works as expected, just in case this is useful to anyone seeing this later!

```sql
{% macro migrate_snapshots_md5_hash() %}
-- assumes that the target has the snapshots in question. If not, run `copy_snapshots_to_target.sql` and then run it

{% if execute %}
  {% for node in graph.nodes.values()
     | selectattr("resource_type", "equalto", "snapshot") %}
  
    {% do log(node.name ~ ", unique_key: " ~ node.config.unique_key, info=true) %}
    -- drop __new version if exists
    -- alter orig to __bkp version
    -- create __new version with md5
    -- drop __new
    {% set query_create_new_hash %}
        -- start {{ node.name }} md5 replacement
        -- create __new_hash table which has all columns except the 
        drop table  {{ ref(node.name) }}__new_hash if exists;
        create table  {{ ref(node.name) }}__new_hash as
            select
            {{ dbt_utils.star(from=ref(node.name), except=['DBT_SCD_ID']) }}
            from {{ref(node.name)}};
        COMMIT;
    {% endset %}
    {% do print(query_create_new_hash) %}
    {% set results = run_query(query_create_new_hash) %} 
    {% do print(results) %}

    {% set query_create_bkp %}
        drop table {{ ref(node.name) }}__bkp if exists;
        alter table {{ ref(node.name) }} rename to {{ ref(node.name) }}__bkp;
        COMMIT;
    {% endset %}
    {% do print(query_create_bkp) %}
    {% set results = run_query(query_create_bkp) %} 
    {% do print(results) %}

    {% set query_create_scd_id %}
        create table {{ ref(node.name) }} as
        select *, {{dbt_utils.surrogate_key([node.config.unique_key, 'DBT_UPDATED_AT'])}} as dbt_scd_id
        from {{ ref(node.name) }}__new_hash;
        COMMIT;
    {% endset %}
    {% do print(query_create_scd_id) %}
    {% set results = run_query(query_create_scd_id) %} 
    {% do print(results) %}
    {% do log(node.name ~ ", script ends here: " ~ node.config.unique_key ~ results, info=true) %}

    {% set query_compare_new_hash_bkp %}
        -- start {{ node.name }} md5 replacement
        -- create __new_hash table which has all columns except the 
            with initial as (
            (select
            {{ dbt_utils.star(from=ref(node.name), except=['DBT_SCD_ID']) }}
            from {{ref(node.name)}}__bkp
            except
            select
            {{ dbt_utils.star(from=ref(node.name), except=['DBT_SCD_ID']) }}
            from {{ref(node.name)}})
            union all
            (select {{ dbt_utils.star(from=ref(node.name), except=['DBT_SCD_ID']) }}
            from {{ref(node.name)}}
            except
            select
            {{ dbt_utils.star(from=ref(node.name), except=['DBT_SCD_ID']) }}
            from {{ref(node.name)}}__bkp))
            select count(*) as number_differences from initial;
    {% endset %}
    {% do print(query_compare_new_hash_bkp) %}
    {% set results = run_query(query_compare_new_hash_bkp) %} 
    {% do print(results.columns[0].values()) %}
    {% do log(node.name ~ ", script ends here: " ~ node.config.unique_key ~ results, info=true) %}

    {% set query_count_scd_comparisons %}
            (select count(distinct dbt_scd_id) from {{ref(node.name)}}__bkp
            )
            union all
            (select count(distinct dbt_scd_id) from {{ref(node.name)}}
            )
            ;
    {% endset %}
    {% set results = run_query(query_count_scd_comparisons) %} 
    {% do print(results.columns[0].values()) %}
  {% endfor %}
{% endif %}

{% endmacro %}

```
update -- added `dbt_update_dt` and a validation output that compares the distinct count of `dbt_scd_id` between the two

**Comment by henrikig** [comment]
Awesome, thanks! We have some more teams who might have to migrate, will test this out then :)
