### ISSUE TITLE
Can connect dbt to netezza on-premise via odbc driver?

### ISSUE THREAD

**Issue by RamesChan** [chop-analytics/dbt-netezza#27]
I would like to know. can I use your code to connect to netezza on-premise by odbc driver. If I can, could you provide a demo for me? Thank you for wasting your time.

**Comment by joemirizio** [comment]
Yes, it is possible to connect to an on-prem Netezza instance. 

This is a community supported adapter and you can learn how to use it by reading the [dbt documentation](https://docs.getdbt.com/docs/introduction) on [configuring a project with `dbt-core`](https://docs.getdbt.com/docs/core/about-core-setup). Unfortunately, we are unable to provide a demo for you, but [the fine folks at dbt labs can](https://www.getdbt.com/contact)!
