### ISSUE TITLE
column macro is_string() always return False

### ISSUE THREAD

**Issue by danielefrigo** [chop-analytics/dbt-netezza#4]
When calling column.is_string() macro, the result is always False (tested with VARCHAR and NVARCHAR columns).
This makes much harder using macros like dbt_utils.union_relations, that leverages this to assign the larger datatype to columns resulting unioning multiple relations.

**Comment by danielefrigo** [comment]
This seems to be related to the data_type_definition in get_columns_in_relation macro.
As far as I understand, this info should not contain length for strings and numbers, so remapping it in the macro could fix the issue.
If you like I can submit a pull request and fix it.

**Comment by joemirizio** [comment]
I believe this was fixed: https://github.com/chop-analytics/dbt-netezza/blob/56e9e7717c9df84c0cf4f1c35e75f07e632b1c82/dbt/adapters/netezza/column.py#L13-L17
