### ISSUE TITLE
CTE prefix in ephemeral models

### ISSUE THREAD

**Issue by danielefrigo** [chop-analytics/dbt-netezza#8]
dbt applies a default prefix __dbt__CTE__ to the cte generated by ephemeral models.
Netezza throws an error when trying to use these ctes joined with others ("WITH Clause syntax not support for system catalog queries"), which is only due to the __ at the beginning of the cte name.
This default prefix can be overridden in the Relation class redefining the add_ephemeral_prefix methid (see Exasol adapter for reference at https://github.com/tglunde/dbt-exasol/blob/e06adb301c6d6865088b60bdcca042e39c4596ab/dbt/adapters/exasol/relation.py#L54).
I'd suggest to override it with a simpler "dbt__CTE__" which should give good uniqueness guarantees and avoid this Netezza compiler error.

**Comment by cnolanminich** [comment]
@danielefrigo I love this suggestion! Will test it out and report back

**Comment by joemirizio** [comment]
This was implemented a while back, so closing this issue. Thanks!
